development:
  adapter: postgresql
  host: localhost
  database: makerspotsdb
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: makerspotsdb
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: makerspotsdb
  host: localhost
  pool: 5
  timeout: 5000
